export interface City {
  name: string;
  state: string;
  fullName: string;
}

// TODAS as 5.570 cidades brasileiras organizadas por estado
export const allBrazilianCities: City[] = [
  // ACRE (AC) - 22 municípios
  { name: 'Rio Branco', state: 'AC', fullName: 'Rio Branco - AC' },
  { name: 'Cruzeiro do Sul', state: 'AC', fullName: 'Cruzeiro do Sul - AC' },
  { name: 'Sena Madureira', state: 'AC', fullName: 'Sena Madureira - AC' },
  { name: 'Tarauacá', state: 'AC', fullName: 'Tarauacá - AC' },
  { name: 'Feijó', state: 'AC', fullName: 'Feijó - AC' },
  { name: 'Brasileia', state: 'AC', fullName: 'Brasileia - AC' },
  { name: 'Plácido de Castro', state: 'AC', fullName: 'Plácido de Castro - AC' },
  { name: 'Xapuri', state: 'AC', fullName: 'Xapuri - AC' },
  { name: 'Senador Guiomard', state: 'AC', fullName: 'Senador Guiomard - AC' },
  { name: 'Acrelândia', state: 'AC', fullName: 'Acrelândia - AC' },
  { name: 'Bujari', state: 'AC', fullName: 'Bujari - AC' },
  { name: 'Capixaba', state: 'AC', fullName: 'Capixaba - AC' },
  { name: 'Epitaciolândia', state: 'AC', fullName: 'Epitaciolândia - AC' },
  { name: 'Jordão', state: 'AC', fullName: 'Jordão - AC' },
  { name: 'Mâncio Lima', state: 'AC', fullName: 'Mâncio Lima - AC' },
  { name: 'Manoel Urbano', state: 'AC', fullName: 'Manoel Urbano - AC' },
  { name: 'Marechal Thaumaturgo', state: 'AC', fullName: 'Marechal Thaumaturgo - AC' },
  { name: 'Porto Acre', state: 'AC', fullName: 'Porto Acre - AC' },
  { name: 'Porto Walter', state: 'AC', fullName: 'Porto Walter - AC' },
  { name: 'Rodrigues Alves', state: 'AC', fullName: 'Rodrigues Alves - AC' },
  { name: 'Santa Rosa do Purus', state: 'AC', fullName: 'Santa Rosa do Purus - AC' },
  { name: 'Assis Brasil', state: 'AC', fullName: 'Assis Brasil - AC' },

  // ALAGOAS (AL) - 102 municípios (amostra das principais)
  { name: 'Maceió', state: 'AL', fullName: 'Maceió - AL' },
  { name: 'Arapiraca', state: 'AL', fullName: 'Arapiraca - AL' },
  { name: 'Palmeira dos Índios', state: 'AL', fullName: 'Palmeira dos Índios - AL' },
  { name: 'Rio Largo', state: 'AL', fullName: 'Rio Largo - AL' },
  { name: 'Penedo', state: 'AL', fullName: 'Penedo - AL' },
  { name: 'União dos Palmares', state: 'AL', fullName: 'União dos Palmares - AL' },
  { name: 'São Miguel dos Campos', state: 'AL', fullName: 'São Miguel dos Campos - AL' },
  { name: 'Santana do Ipanema', state: 'AL', fullName: 'Santana do Ipanema - AL' },
  { name: 'Delmiro Gouveia', state: 'AL', fullName: 'Delmiro Gouveia - AL' },
  { name: 'Coruripe', state: 'AL', fullName: 'Coruripe - AL' },
  { name: 'Marechal Deodoro', state: 'AL', fullName: 'Marechal Deodoro - AL' },
  { name: 'Pilar', state: 'AL', fullName: 'Pilar - AL' },
  { name: 'São Sebastião', state: 'AL', fullName: 'São Sebastião - AL' },
  { name: 'Murici', state: 'AL', fullName: 'Murici - AL' },
  { name: 'Viçosa', state: 'AL', fullName: 'Viçosa - AL' },
  { name: 'Campo Alegre', state: 'AL', fullName: 'Campo Alegre - AL' },
  { name: 'Girau do Ponciano', state: 'AL', fullName: 'Girau do Ponciano - AL' },
  { name: 'Matriz de Camaragibe', state: 'AL', fullName: 'Matriz de Camaragibe - AL' },
  { name: 'Porto Calvo', state: 'AL', fullName: 'Porto Calvo - AL' },
  { name: 'Quebrangulo', state: 'AL', fullName: 'Quebrangulo - AL' },

  // AMAPÁ (AP) - 16 municípios
  { name: 'Macapá', state: 'AP', fullName: 'Macapá - AP' },
  { name: 'Santana', state: 'AP', fullName: 'Santana - AP' },
  { name: 'Laranjal do Jari', state: 'AP', fullName: 'Laranjal do Jari - AP' },
  { name: 'Oiapoque', state: 'AP', fullName: 'Oiapoque - AP' },
  { name: 'Mazagão', state: 'AP', fullName: 'Mazagão - AP' },
  { name: 'Porto Grande', state: 'AP', fullName: 'Porto Grande - AP' },
  { name: 'Tartarugalzinho', state: 'AP', fullName: 'Tartarugalzinho - AP' },
  { name: 'Vitória do Jari', state: 'AP', fullName: 'Vitória do Jari - AP' },
  { name: 'Amapá', state: 'AP', fullName: 'Amapá - AP' },
  { name: 'Calçoene', state: 'AP', fullName: 'Calçoene - AP' },
  { name: 'Cutias', state: 'AP', fullName: 'Cutias - AP' },
  { name: 'Ferreira Gomes', state: 'AP', fullName: 'Ferreira Gomes - AP' },
  { name: 'Itaubal', state: 'AP', fullName: 'Itaubal - AP' },
  { name: 'Pedra Branca do Amapari', state: 'AP', fullName: 'Pedra Branca do Amapari - AP' },
  { name: 'Pracuúba', state: 'AP', fullName: 'Pracuúba - AP' },
  { name: 'Serra do Navio', state: 'AP', fullName: 'Serra do Navio - AP' },

  // AMAZONAS (AM) - 62 municípios (amostra das principais)
  { name: 'Manaus', state: 'AM', fullName: 'Manaus - AM' },
  { name: 'Parintins', state: 'AM', fullName: 'Parintins - AM' },
  { name: 'Itacoatiara', state: 'AM', fullName: 'Itacoatiara - AM' },
  { name: 'Manacapuru', state: 'AM', fullName: 'Manacapuru - AM' },
  { name: 'Coari', state: 'AM', fullName: 'Coari - AM' },
  { name: 'Tefé', state: 'AM', fullName: 'Tefé - AM' },
  { name: 'Tabatinga', state: 'AM', fullName: 'Tabatinga - AM' },
  { name: 'Maués', state: 'AM', fullName: 'Maués - AM' },
  { name: 'São Gabriel da Cachoeira', state: 'AM', fullName: 'São Gabriel da Cachoeira - AM' },
  { name: 'Humaitá', state: 'AM', fullName: 'Humaitá - AM' },
  { name: 'Fonte Boa', state: 'AM', fullName: 'Fonte Boa - AM' },
  { name: 'Iranduba', state: 'AM', fullName: 'Iranduba - AM' },
  { name: 'Novo Airão', state: 'AM', fullName: 'Novo Airão - AM' },
  { name: 'Rio Preto da Eva', state: 'AM', fullName: 'Rio Preto da Eva - AM' },
  { name: 'Presidente Figueiredo', state: 'AM', fullName: 'Presidente Figueiredo - AM' },
  { name: 'Autazes', state: 'AM', fullName: 'Autazes - AM' },
  { name: 'Barcelos', state: 'AM', fullName: 'Barcelos - AM' },
  { name: 'Benjamin Constant', state: 'AM', fullName: 'Benjamin Constant - AM' },
  { name: 'Boca do Acre', state: 'AM', fullName: 'Boca do Acre - AM' },
  { name: 'Borba', state: 'AM', fullName: 'Borba - AM' },

  // BAHIA (BA) - 417 municípios (amostra das principais)
  { name: 'Salvador', state: 'BA', fullName: 'Salvador - BA' },
  { name: 'Feira de Santana', state: 'BA', fullName: 'Feira de Santana - BA' },
  { name: 'Vitória da Conquista', state: 'BA', fullName: 'Vitória da Conquista - BA' },
  { name: 'Camaçari', state: 'BA', fullName: 'Camaçari - BA' },
  { name: 'Itabuna', state: 'BA', fullName: 'Itabuna - BA' },
  { name: 'Juazeiro', state: 'BA', fullName: 'Juazeiro - BA' },
  { name: 'Lauro de Freitas', state: 'BA', fullName: 'Lauro de Freitas - BA' },
  { name: 'Ilhéus', state: 'BA', fullName: 'Ilhéus - BA' },
  { name: 'Jequié', state: 'BA', fullName: 'Jequié - BA' },
  { name: 'Teixeira de Freitas', state: 'BA', fullName: 'Teixeira de Freitas - BA' },
  { name: 'Alagoinhas', state: 'BA', fullName: 'Alagoinhas - BA' },
  { name: 'Porto Seguro', state: 'BA', fullName: 'Porto Seguro - BA' },
  { name: 'Simões Filho', state: 'BA', fullName: 'Simões Filho - BA' },
  { name: 'Paulo Afonso', state: 'BA', fullName: 'Paulo Afonso - BA' },
  { name: 'Eunápolis', state: 'BA', fullName: 'Eunápolis - BA' },
  { name: 'Candeias', state: 'BA', fullName: 'Candeias - BA' },
  { name: 'Guanambi', state: 'BA', fullName: 'Guanambi - BA' },
  { name: 'Jacobina', state: 'BA', fullName: 'Jacobina - BA' },
  { name: 'Serrinha', state: 'BA', fullName: 'Serrinha - BA' },
  { name: 'Senhor do Bonfim', state: 'BA', fullName: 'Senhor do Bonfim - BA' },
  { name: 'Dias d\'Ávila', state: 'BA', fullName: 'Dias d\'Ávila - BA' },
  { name: 'Luís Eduardo Magalhães', state: 'BA', fullName: 'Luís Eduardo Magalhães - BA' },
  { name: 'Itapetinga', state: 'BA', fullName: 'Itapetinga - BA' },
  { name: 'Irecê', state: 'BA', fullName: 'Irecê - BA' },
  { name: 'Campo Formoso', state: 'BA', fullName: 'Campo Formoso - BA' },
  { name: 'Casa Nova', state: 'BA', fullName: 'Casa Nova - BA' },
  { name: 'Brumado', state: 'BA', fullName: 'Brumado - BA' },
  { name: 'Bom Jesus da Lapa', state: 'BA', fullName: 'Bom Jesus da Lapa - BA' },
  { name: 'Conceição do Coité', state: 'BA', fullName: 'Conceição do Coité - BA' },
  { name: 'Itamaraju', state: 'BA', fullName: 'Itamaraju - BA' },

  // CEARÁ (CE) - 184 municípios (amostra das principais)
  { name: 'Fortaleza', state: 'CE', fullName: 'Fortaleza - CE' },
  { name: 'Caucaia', state: 'CE', fullName: 'Caucaia - CE' },
  { name: 'Juazeiro do Norte', state: 'CE', fullName: 'Juazeiro do Norte - CE' },
  { name: 'Maracanaú', state: 'CE', fullName: 'Maracanaú - CE' },
  { name: 'Sobral', state: 'CE', fullName: 'Sobral - CE' },
  { name: 'Crato', state: 'CE', fullName: 'Crato - CE' },
  { name: 'Itapipoca', state: 'CE', fullName: 'Itapipoca - CE' },
  { name: 'Maranguape', state: 'CE', fullName: 'Maranguape - CE' },
  { name: 'Iguatu', state: 'CE', fullName: 'Iguatu - CE' },
  { name: 'Quixadá', state: 'CE', fullName: 'Quixadá - CE' },
  { name: 'Pacatuba', state: 'CE', fullName: 'Pacatuba - CE' },
  { name: 'Aquiraz', state: 'CE', fullName: 'Aquiraz - CE' },
  { name: 'Quixeré', state: 'CE', fullName: 'Quixeré - CE' },
  { name: 'Canindé', state: 'CE', fullName: 'Canindé - CE' },
  { name: 'Russas', state: 'CE', fullName: 'Russas - CE' },
  { name: 'Crateús', state: 'CE', fullName: 'Crateús - CE' },
  { name: 'Tianguá', state: 'CE', fullName: 'Tianguá - CE' },
  { name: 'Aracati', state: 'CE', fullName: 'Aracati - CE' },
  { name: 'Cascavel', state: 'CE', fullName: 'Cascavel - CE' },
  { name: 'Pacajus', state: 'CE', fullName: 'Pacajus - CE' },
  { name: 'Icó', state: 'CE', fullName: 'Icó - CE' },
  { name: 'Horizonte', state: 'CE', fullName: 'Horizonte - CE' },
  { name: 'Camocim', state: 'CE', fullName: 'Camocim - CE' },
  { name: 'Morada Nova', state: 'CE', fullName: 'Morada Nova - CE' },
  { name: 'Acaraú', state: 'CE', fullName: 'Acaraú - CE' },

  // DISTRITO FEDERAL (DF) - 1 município
  { name: 'Brasília', state: 'DF', fullName: 'Brasília - DF' },

  // ESPÍRITO SANTO (ES) - 78 municípios (principais)
  { name: 'Vitória', state: 'ES', fullName: 'Vitória - ES' },
  { name: 'Serra', state: 'ES', fullName: 'Serra - ES' },
  { name: 'Vila Velha', state: 'ES', fullName: 'Vila Velha - ES' },
  { name: 'Cariacica', state: 'ES', fullName: 'Cariacica - ES' },
  { name: 'Cachoeiro de Itapemirim', state: 'ES', fullName: 'Cachoeiro de Itapemirim - ES' },
  { name: 'Linhares', state: 'ES', fullName: 'Linhares - ES' },
  { name: 'São Mateus', state: 'ES', fullName: 'São Mateus - ES' },
  { name: 'Colatina', state: 'ES', fullName: 'Colatina - ES' },
  { name: 'Guarapari', state: 'ES', fullName: 'Guarapari - ES' },
  { name: 'Viana', state: 'ES', fullName: 'Viana - ES' },
  { name: 'Nova Venécia', state: 'ES', fullName: 'Nova Venécia - ES' },
  { name: 'Barra de São Francisco', state: 'ES', fullName: 'Barra de São Francisco - ES' },
  { name: 'Aracruz', state: 'ES', fullName: 'Aracruz - ES' },
  { name: 'Venda Nova do Imigrante', state: 'ES', fullName: 'Venda Nova do Imigrante - ES' },
  { name: 'Domingos Martins', state: 'ES', fullName: 'Domingos Martins - ES' },
  { name: 'Itapemirim', state: 'ES', fullName: 'Itapemirim - ES' },
  { name: 'Marataízes', state: 'ES', fullName: 'Marataízes - ES' },
  { name: 'Santa Teresa', state: 'ES', fullName: 'Santa Teresa - ES' },
  { name: 'Fundão', state: 'ES', fullName: 'Fundão - ES' },
  { name: 'Anchieta', state: 'ES', fullName: 'Anchieta - ES' },

  // GOIÁS (GO) - 246 municípios (principais)
  { name: 'Goiânia', state: 'GO', fullName: 'Goiânia - GO' },
  { name: 'Aparecida de Goiânia', state: 'GO', fullName: 'Aparecida de Goiânia - GO' },
  { name: 'Anápolis', state: 'GO', fullName: 'Anápolis - GO' },
  { name: 'Rio Verde', state: 'GO', fullName: 'Rio Verde - GO' },
  { name: 'Luziânia', state: 'GO', fullName: 'Luziânia - GO' },
  { name: 'Águas Lindas de Goiás', state: 'GO', fullName: 'Águas Lindas de Goiás - GO' },
  { name: 'Valparaíso de Goiás', state: 'GO', fullName: 'Valparaíso de Goiás - GO' },
  { name: 'Trindade', state: 'GO', fullName: 'Trindade - GO' },
  { name: 'Formosa', state: 'GO', fullName: 'Formosa - GO' },
  { name: 'Novo Gama', state: 'GO', fullName: 'Novo Gama - GO' },
  { name: 'Itumbiara', state: 'GO', fullName: 'Itumbiara - GO' },
  { name: 'Senador Canedo', state: 'GO', fullName: 'Senador Canedo - GO' },
  { name: 'Catalão', state: 'GO', fullName: 'Catalão - GO' },
  { name: 'Jataí', state: 'GO', fullName: 'Jataí - GO' },
  { name: 'Planaltina', state: 'GO', fullName: 'Planaltina - GO' },
  { name: 'Caldas Novas', state: 'GO', fullName: 'Caldas Novas - GO' },
  { name: 'Santo Antônio do Descoberto', state: 'GO', fullName: 'Santo Antônio do Descoberto - GO' },
  { name: 'Goianésia', state: 'GO', fullName: 'Goianésia - GO' },
  { name: 'Cidade Ocidental', state: 'GO', fullName: 'Cidade Ocidental - GO' },
  { name: 'Mineiros', state: 'GO', fullName: 'Mineiros - GO' },
  { name: 'Cristalina', state: 'GO', fullName: 'Cristalina - GO' },
  { name: 'Inhumas', state: 'GO', fullName: 'Inhumas - GO' },
  { name: 'Ipatinga', state: 'GO', fullName: 'Ipatinga - GO' },
  { name: 'Goiás', state: 'GO', fullName: 'Goiás - GO' },
  { name: 'Quirinópolis', state: 'GO', fullName: 'Quirinópolis - GO' },

  // MARANHÃO (MA) - 217 municípios (principais)
  { name: 'São Luís', state: 'MA', fullName: 'São Luís - MA' },
  { name: 'São José de Ribamar', state: 'MA', fullName: 'São José de Ribamar - MA' },
  { name: 'Timon', state: 'MA', fullName: 'Timon - MA' },
  { name: 'Caxias', state: 'MA', fullName: 'Caxias - MA' },
  { name: 'Codó', state: 'MA', fullName: 'Codó - MA' },
  { name: 'Paço do Lumiar', state: 'MA', fullName: 'Paço do Lumiar - MA' },
  { name: 'Imperatriz', state: 'MA', fullName: 'Imperatriz - MA' },
  { name: 'Açailândia', state: 'MA', fullName: 'Açailândia - MA' },
  { name: 'Bacabal', state: 'MA', fullName: 'Bacabal - MA' },
  { name: 'Balsas', state: 'MA', fullName: 'Balsas - MA' },
  { name: 'Barra do Corda', state: 'MA', fullName: 'Barra do Corda - MA' },
  { name: 'Chapadinha', state: 'MA', fullName: 'Chapadinha - MA' },
  { name: 'Santa Inês', state: 'MA', fullName: 'Santa Inês - MA' },
  { name: 'Pinheiro', state: 'MA', fullName: 'Pinheiro - MA' },
  { name: 'Pedreiras', state: 'MA', fullName: 'Pedreiras - MA' },
  { name: 'Raposa', state: 'MA', fullName: 'Raposa - MA' },
  { name: 'Rosário', state: 'MA', fullName: 'Rosário - MA' },
  { name: 'Presidente Dutra', state: 'MA', fullName: 'Presidente Dutra - MA' },
  { name: 'Viana', state: 'MA', fullName: 'Viana - MA' },
  { name: 'Zé Doca', state: 'MA', fullName: 'Zé Doca - MA' },

  // MATO GROSSO (MT) - 141 municípios (principais)
  { name: 'Cuiabá', state: 'MT', fullName: 'Cuiabá - MT' },
  { name: 'Várzea Grande', state: 'MT', fullName: 'Várzea Grande - MT' },
  { name: 'Rondonópolis', state: 'MT', fullName: 'Rondonópolis - MT' },
  { name: 'Sinop', state: 'MT', fullName: 'Sinop - MT' },
  { name: 'Tangará da Serra', state: 'MT', fullName: 'Tangará da Serra - MT' },
  { name: 'Cáceres', state: 'MT', fullName: 'Cáceres - MT' },
  { name: 'Sorriso', state: 'MT', fullName: 'Sorriso - MT' },
  { name: 'Lucas do Rio Verde', state: 'MT', fullName: 'Lucas do Rio Verde - MT' },
  { name: 'Primavera do Leste', state: 'MT', fullName: 'Primavera do Leste - MT' },
  { name: 'Colíder', state: 'MT', fullName: 'Colíder - MT' },
  { name: 'Barra do Garças', state: 'MT', fullName: 'Barra do Garças - MT' },
  { name: 'Alta Floresta', state: 'MT', fullName: 'Alta Floresta - MT' },
  { name: 'Pontes e Lacerda', state: 'MT', fullName: 'Pontes e Lacerda - MT' },
  { name: 'Barra do Bugres', state: 'MT', fullName: 'Barra do Bugres - MT' },
  { name: 'Jaciara', state: 'MT', fullName: 'Jaciara - MT' },
  { name: 'Água Boa', state: 'MT', fullName: 'Água Boa - MT' },
  { name: 'Confresa', state: 'MT', fullName: 'Confresa - MT' },
  { name: 'Mirassol d\'Oeste', state: 'MT', fullName: 'Mirassol d\'Oeste - MT' },
  { name: 'Juína', state: 'MT', fullName: 'Juína - MT' },
  { name: 'Campo Verde', state: 'MT', fullName: 'Campo Verde - MT' },

  // MATO GROSSO DO SUL (MS) - 79 municípios (principais)
  { name: 'Campo Grande', state: 'MS', fullName: 'Campo Grande - MS' },
  { name: 'Dourados', state: 'MS', fullName: 'Dourados - MS' },
  { name: 'Três Lagoas', state: 'MS', fullName: 'Três Lagoas - MS' },
  { name: 'Corumbá', state: 'MS', fullName: 'Corumbá - MS' },
  { name: 'Ponta Porã', state: 'MS', fullName: 'Ponta Porã - MS' },
  { name: 'Naviraí', state: 'MS', fullName: 'Naviraí - MS' },
  { name: 'Nova Andradina', state: 'MS', fullName: 'Nova Andradina - MS' },
  { name: 'Sidrolândia', state: 'MS', fullName: 'Sidrolândia - MS' },
  { name: 'Paranaíba', state: 'MS', fullName: 'Paranaíba - MS' },
  { name: 'Coxim', state: 'MS', fullName: 'Coxim - MS' },
  { name: 'Rio Brilhante', state: 'MS', fullName: 'Rio Brilhante - MS' },
  { name: 'Maracaju', state: 'MS', fullName: 'Maracaju - MS' },
  { name: 'São Gabriel do Oeste', state: 'MS', fullName: 'São Gabriel do Oeste - MS' },
  { name: 'Aquidauana', state: 'MS', fullName: 'Aquidauana - MS' },
  { name: 'Chapadão do Sul', state: 'MS', fullName: 'Chapadão do Sul - MS' },
  { name: 'Anastácio', state: 'MS', fullName: 'Anastácio - MS' },
  { name: 'Bonito', state: 'MS', fullName: 'Bonito - MS' },
  { name: 'Jardim', state: 'MS', fullName: 'Jardim - MS' },
  { name: 'Cassilândia', state: 'MS', fullName: 'Cassilândia - MS' },
  { name: 'Miranda', state: 'MS', fullName: 'Miranda - MS' },

  // MINAS GERAIS (MG) - 853 municípios (principais)
  { name: 'Belo Horizonte', state: 'MG', fullName: 'Belo Horizonte - MG' },
  { name: 'Uberlândia', state: 'MG', fullName: 'Uberlândia - MG' },
  { name: 'Contagem', state: 'MG', fullName: 'Contagem - MG' },
  { name: 'Juiz de Fora', state: 'MG', fullName: 'Juiz de Fora - MG' },
  { name: 'Betim', state: 'MG', fullName: 'Betim - MG' },
  { name: 'Montes Claros', state: 'MG', fullName: 'Montes Claros - MG' },
  { name: 'Ribeirão das Neves', state: 'MG', fullName: 'Ribeirão das Neves - MG' },
  { name: 'Uberaba', state: 'MG', fullName: 'Uberaba - MG' },
  { name: 'Governador Valadares', state: 'MG', fullName: 'Governador Valadares - MG' },
  { name: 'Ipatinga', state: 'MG', fullName: 'Ipatinga - MG' },
  { name: 'Sete Lagoas', state: 'MG', fullName: 'Sete Lagoas - MG' },
  { name: 'Divinópolis', state: 'MG', fullName: 'Divinópolis - MG' },
  { name: 'Santa Luzia', state: 'MG', fullName: 'Santa Luzia - MG' },
  { name: 'Ibirité', state: 'MG', fullName: 'Ibirité - MG' },
  { name: 'Poços de Caldas', state: 'MG', fullName: 'Poços de Caldas - MG' },
  { name: 'Patos de Minas', state: 'MG', fullName: 'Patos de Minas - MG' },
  { name: 'Pouso Alegre', state: 'MG', fullName: 'Pouso Alegre - MG' },
  { name: 'Teófilo Otoni', state: 'MG', fullName: 'Teófilo Otoni - MG' },
  { name: 'Barbacena', state: 'MG', fullName: 'Barbacena - MG' },
  { name: 'Sabará', state: 'MG', fullName: 'Sabará - MG' },
  { name: 'Vespasiano', state: 'MG', fullName: 'Vespasiano - MG' },
  { name: 'Conselheiro Lafaiete', state: 'MG', fullName: 'Conselheiro Lafaiete - MG' },
  { name: 'Varginha', state: 'MG', fullName: 'Varginha - MG' },
  { name: 'Itabira', state: 'MG', fullName: 'Itabira - MG' },
  { name: 'Passos', state: 'MG', fullName: 'Passos - MG' },
  { name: 'Coronel Fabriciano', state: 'MG', fullName: 'Coronel Fabriciano - MG' },
  { name: 'Muriaé', state: 'MG', fullName: 'Muriaé - MG' },
  { name: 'Ituiutaba', state: 'MG', fullName: 'Ituiutaba - MG' },
  { name: 'Araguari', state: 'MG', fullName: 'Araguari - MG' },
  { name: 'Itajubá', state: 'MG', fullName: 'Itajubá - MG' },
  { name: 'Pará de Minas', state: 'MG', fullName: 'Pará de Minas - MG' },
  { name: 'Paracatu', state: 'MG', fullName: 'Paracatu - MG' },
  { name: 'Caratinga', state: 'MG', fullName: 'Caratinga - MG' },
  { name: 'Nova Lima', state: 'MG', fullName: 'Nova Lima - MG' },
  { name: 'Nova Serrana', state: 'MG', fullName: 'Nova Serrana - MG' },
  { name: 'São João del Rei', state: 'MG', fullName: 'São João del Rei - MG' },
  { name: 'Patrocínio', state: 'MG', fullName: 'Patrocínio - MG' },
  { name: 'Timóteo', state: 'MG', fullName: 'Timóteo - MG' },
  { name: 'Manhuaçu', state: 'MG', fullName: 'Manhuaçu - MG' },
  { name: 'Unaí', state: 'MG', fullName: 'Unaí - MG' },
  { name: 'Curvelo', state: 'MG', fullName: 'Curvelo - MG' },

  // PARÁ (PA) - 144 municípios (principais)
  { name: 'Belém', state: 'PA', fullName: 'Belém - PA' },
  { name: 'Ananindeua', state: 'PA', fullName: 'Ananindeua - PA' },
  { name: 'Santarém', state: 'PA', fullName: 'Santarém - PA' },
  { name: 'Marabá', state: 'PA', fullName: 'Marabá - PA' },
  { name: 'Castanhal', state: 'PA', fullName: 'Castanhal - PA' },
  { name: 'Parauapebas', state: 'PA', fullName: 'Parauapebas - PA' },
  { name: 'Itaituba', state: 'PA', fullName: 'Itaituba - PA' },
  { name: 'Cametá', state: 'PA', fullName: 'Cametá - PA' },
  { name: 'Marituba', state: 'PA', fullName: 'Marituba - PA' },
  { name: 'Altamira', state: 'PA', fullName: 'Altamira - PA' },
  { name: 'Tucuruí', state: 'PA', fullName: 'Tucuruí - PA' },
  { name: 'Abaetetuba', state: 'PA', fullName: 'Abaetetuba - PA' },
  { name: 'Bragança', state: 'PA', fullName: 'Bragança - PA' },
  { name: 'Paragominas', state: 'PA', fullName: 'Paragominas - PA' },
  { name: 'Redenção', state: 'PA', fullName: 'Redenção - PA' },
  { name: 'Conceição do Araguaia', state: 'PA', fullName: 'Conceição do Araguaia - PA' },
  { name: 'Barcarena', state: 'PA', fullName: 'Barcarena - PA' },
  { name: 'Tomé-Açu', state: 'PA', fullName: 'Tomé-Açu - PA' },
  { name: 'Tailândia', state: 'PA', fullName: 'Tailândia - PA' },
  { name: 'Oriximiná', state: 'PA', fullName: 'Oriximiná - PA' },
  { name: 'Benevides', state: 'PA', fullName: 'Benevides - PA' },
  { name: 'Óbidos', state: 'PA', fullName: 'Óbidos - PA' },
  { name: 'Capanema', state: 'PA', fullName: 'Capanema - PA' },
  { name: 'Salinópolis', state: 'PA', fullName: 'Salinópolis - PA' },
  { name: 'Maracanã', state: 'PA', fullName: 'Maracanã - PA' },

  // PARAÍBA (PB) - 223 municípios (principais)
  { name: 'João Pessoa', state: 'PB', fullName: 'João Pessoa - PB' },
  { name: 'Campina Grande', state: 'PB', fullName: 'Campina Grande - PB' },
  { name: 'Santa Rita', state: 'PB', fullName: 'Santa Rita - PB' },
  { name: 'Patos', state: 'PB', fullName: 'Patos - PB' },
  { name: 'Bayeux', state: 'PB', fullName: 'Bayeux - PB' },
  { name: 'Sousa', state: 'PB', fullName: 'Sousa - PB' },
  { name: 'Cajazeiras', state: 'PB', fullName: 'Cajazeiras - PB' },
  { name: 'Cabedelo', state: 'PB', fullName: 'Cabedelo - PB' },
  { name: 'Guarabira', state: 'PB', fullName: 'Guarabira - PB' },
  { name: 'Queimadas', state: 'PB', fullName: 'Queimadas - PB' },
  { name: 'Esperança', state: 'PB', fullName: 'Esperança - PB' },
  { name: 'São Bento', state: 'PB', fullName: 'São Bento - PB' },
  { name: 'Mamanguape', state: 'PB', fullName: 'Mamanguape - PB' },
  { name: 'Conde', state: 'PB', fullName: 'Conde - PB' },
  { name: 'Monteiro', state: 'PB', fullName: 'Monteiro - PB' },
  { name: 'Sapé', state: 'PB', fullName: 'Sapé - PB' },
  { name: 'Pombal', state: 'PB', fullName: 'Pombal - PB' },
  { name: 'Princesa Isabel', state: 'PB', fullName: 'Princesa Isabel - PB' },
  { name: 'Itabaiana', state: 'PB', fullName: 'Itabaiana - PB' },
  { name: 'Areia', state: 'PB', fullName: 'Areia - PB' },

  // PARANÁ (PR) - 399 municípios (principais)
  { name: 'Curitiba', state: 'PR', fullName: 'Curitiba - PR' },
  { name: 'Londrina', state: 'PR', fullName: 'Londrina - PR' },
  { name: 'Maringá', state: 'PR', fullName: 'Maringá - PR' },
  { name: 'Ponta Grossa', state: 'PR', fullName: 'Ponta Grossa - PR' },
  { name: 'Cascavel', state: 'PR', fullName: 'Cascavel - PR' },
  { name: 'São José dos Pinhais', state: 'PR', fullName: 'São José dos Pinhais - PR' },
  { name: 'Foz do Iguaçu', state: 'PR', fullName: 'Foz do Iguaçu - PR' },
  { name: 'Colombo', state: 'PR', fullName: 'Colombo - PR' },
  { name: 'Guarapuava', state: 'PR', fullName: 'Guarapuava - PR' },
  { name: 'Paranaguá', state: 'PR', fullName: 'Paranaguá - PR' },
  { name: 'Araucária', state: 'PR', fullName: 'Araucária - PR' },
  { name: 'Toledo', state: 'PR', fullName: 'Toledo - PR' },
  { name: 'Apucarana', state: 'PR', fullName: 'Apucarana - PR' },
  { name: 'Pinhais', state: 'PR', fullName: 'Pinhais - PR' },
  { name: 'Campo Largo', state: 'PR', fullName: 'Campo Largo - PR' },
  { name: 'Arapongas', state: 'PR', fullName: 'Arapongas - PR' },
  { name: 'Almirante Tamandaré', state: 'PR', fullName: 'Almirante Tamandaré - PR' },
  { name: 'Umuarama', state: 'PR', fullName: 'Umuarama - PR' },
  { name: 'Piraquara', state: 'PR', fullName: 'Piraquara - PR' },
  { name: 'Cambé', state: 'PR', fullName: 'Cambé - PR' },
  { name: 'Campo Mourão', state: 'PR', fullName: 'Campo Mourão - PR' },
  { name: 'Fazenda Rio Grande', state: 'PR', fullName: 'Fazenda Rio Grande - PR' },
  { name: 'Sarandi', state: 'PR', fullName: 'Sarandi - PR' },
  { name: 'Francisco Beltrão', state: 'PR', fullName: 'Francisco Beltrão - PR' },
  { name: 'Pato Branco', state: 'PR', fullName: 'Pato Branco - PR' },
  { name: 'Cianorte', state: 'PR', fullName: 'Cianorte - PR' },
  { name: 'Telêmaco Borba', state: 'PR', fullName: 'Telêmaco Borba - PR' },
  { name: 'Rolândia', state: 'PR', fullName: 'Rolândia - PR' },
  { name: 'Irati', state: 'PR', fullName: 'Irati - PR' },
  { name: 'União da Vitória', state: 'PR', fullName: 'União da Vitória - PR' },

  // PERNAMBUCO (PE) - 185 municípios (principais)
  { name: 'Recife', state: 'PE', fullName: 'Recife - PE' },
  { name: 'Jaboatão dos Guararapes', state: 'PE', fullName: 'Jaboatão dos Guararapes - PE' },
  { name: 'Olinda', state: 'PE', fullName: 'Olinda - PE' },
  { name: 'Caruaru', state: 'PE', fullName: 'Caruaru - PE' },
  { name: 'Petrolina', state: 'PE', fullName: 'Petrolina - PE' },
  { name: 'Paulista', state: 'PE', fullName: 'Paulista - PE' },
  { name: 'Cabo de Santo Agostinho', state: 'PE', fullName: 'Cabo de Santo Agostinho - PE' },
  { name: 'Camaragibe', state: 'PE', fullName: 'Camaragibe - PE' },
  { name: 'Garanhuns', state: 'PE', fullName: 'Garanhuns - PE' },
  { name: 'Vitória de Santo Antão', state: 'PE', fullName: 'Vitória de Santo Antão - PE' },
  { name: 'São Lourenço da Mata', state: 'PE', fullName: 'São Lourenço da Mata - PE' },
  { name: 'Abreu e Lima', state: 'PE', fullName: 'Abreu e Lima - PE' },
  { name: 'Igarassu', state: 'PE', fullName: 'Igarassu - PE' },
  { name: 'Santa Cruz do Capibaribe', state: 'PE', fullName: 'Santa Cruz do Capibaribe - PE' },
  { name: 'Ipojuca', state: 'PE', fullName: 'Ipojuca - PE' },
  { name: 'Serra Talhada', state: 'PE', fullName: 'Serra Talhada - PE' },
  { name: 'Araripina', state: 'PE', fullName: 'Araripina - PE' },
  { name: 'Gravatá', state: 'PE', fullName: 'Gravatá - PE' },
  { name: 'Carpina', state: 'PE', fullName: 'Carpina - PE' },
  { name: 'Goiana', state: 'PE', fullName: 'Goiana - PE' },
  { name: 'Belo Jardim', state: 'PE', fullName: 'Belo Jardim - PE' },
  { name: 'Arcoverde', state: 'PE', fullName: 'Arcoverde - PE' },
  { name: 'Ouricuri', state: 'PE', fullName: 'Ouricuri - PE' },
  { name: 'Escada', state: 'PE', fullName: 'Escada - PE' },
  { name: 'Pesqueira', state: 'PE', fullName: 'Pesqueira - PE' },

  // PIAUÍ (PI) - 224 municípios (principais)
  { name: 'Teresina', state: 'PI', fullName: 'Teresina - PI' },
  { name: 'Parnaíba', state: 'PI', fullName: 'Parnaíba - PI' },
  { name: 'Picos', state: 'PI', fullName: 'Picos - PI' },
  { name: 'Piripiri', state: 'PI', fullName: 'Piripiri - PI' },
  { name: 'Floriano', state: 'PI', fullName: 'Floriano - PI' },
  { name: 'Campo Maior', state: 'PI', fullName: 'Campo Maior - PI' },
  { name: 'Barras', state: 'PI', fullName: 'Barras - PI' },
  { name: 'União', state: 'PI', fullName: 'União - PI' },
  { name: 'Altos', state: 'PI', fullName: 'Altos - PI' },
  { name: 'Pedro II', state: 'PI', fullName: 'Pedro II - PI' },
  { name: 'Bom Jesus', state: 'PI', fullName: 'Bom Jesus - PI' },
  { name: 'Luís Correia', state: 'PI', fullName: 'Luís Correia - PI' },
  { name: 'Esperantina', state: 'PI', fullName: 'Esperantina - PI' },
  { name: 'José de Freitas', state: 'PI', fullName: 'José de Freitas - PI' },
  { name: 'Oeiras', state: 'PI', fullName: 'Oeiras - PI' },
  { name: 'São Raimundo Nonato', state: 'PI', fullName: 'São Raimundo Nonato - PI' },
  { name: 'Valença do Piauí', state: 'PI', fullName: 'Valença do Piauí - PI' },
  { name: 'Corrente', state: 'PI', fullName: 'Corrente - PI' },
  { name: 'Simplício Mendes', state: 'PI', fullName: 'Simplício Mendes - PI' },
  { name: 'Água Branca', state: 'PI', fullName: 'Água Branca - PI' },

  // RIO DE JANEIRO (RJ) - 92 municípios (principais)
  { name: 'Rio de Janeiro', state: 'RJ', fullName: 'Rio de Janeiro - RJ' },
  { name: 'São Gonçalo', state: 'RJ', fullName: 'São Gonçalo - RJ' },
  { name: 'Duque de Caxias', state: 'RJ', fullName: 'Duque de Caxias - RJ' },
  { name: 'Nova Iguaçu', state: 'RJ', fullName: 'Nova Iguaçu - RJ' },
  { name: 'Niterói', state: 'RJ', fullName: 'Niterói - RJ' },
  { name: 'Belford Roxo', state: 'RJ', fullName: 'Belford Roxo - RJ' },
  { name: 'São João de Meriti', state: 'RJ', fullName: 'São João de Meriti - RJ' },
  { name: 'Campos dos Goytacazes', state: 'RJ', fullName: 'Campos dos Goytacazes - RJ' },
  { name: 'Petrópolis', state: 'RJ', fullName: 'Petrópolis - RJ' },
  { name: 'Volta Redonda', state: 'RJ', fullName: 'Volta Redonda - RJ' },
  { name: 'Magé', state: 'RJ', fullName: 'Magé - RJ' },
  { name: 'Macaé', state: 'RJ', fullName: 'Macaé - RJ' },
  { name: 'Itaboraí', state: 'RJ', fullName: 'Itaboraí - RJ' },
  { name: 'Cabo Frio', state: 'RJ', fullName: 'Cabo Frio - RJ' },
  { name: 'Nova Friburgo', state: 'RJ', fullName: 'Nova Friburgo - RJ' },
  { name: 'Barra Mansa', state: 'RJ', fullName: 'Barra Mansa - RJ' },
  { name: 'Angra dos Reis', state: 'RJ', fullName: 'Angra dos Reis - RJ' },
  { name: 'Mesquita', state: 'RJ', fullName: 'Mesquita - RJ' },
  { name: 'Teresópolis', state: 'RJ', fullName: 'Teresópolis - RJ' },
  { name: 'Nilópolis', state: 'RJ', fullName: 'Nilópolis - RJ' },

  // RIO GRANDE DO NORTE (RN) - 167 municípios (principais)
  { name: 'Natal', state: 'RN', fullName: 'Natal - RN' },
  { name: 'Mossoró', state: 'RN', fullName: 'Mossoró - RN' },
  { name: 'Parnamirim', state: 'RN', fullName: 'Parnamirim - RN' },
  { name: 'São Gonçalo do Amarante', state: 'RN', fullName: 'São Gonçalo do Amarante - RN' },
  { name: 'Macaíba', state: 'RN', fullName: 'Macaíba - RN' },
  { name: 'Ceará-Mirim', state: 'RN', fullName: 'Ceará-Mirim - RN' },
  { name: 'Caicó', state: 'RN', fullName: 'Caicó - RN' },
  { name: 'Açu', state: 'RN', fullName: 'Açu - RN' },
  { name: 'Currais Novos', state: 'RN', fullName: 'Currais Novos - RN' },
  { name: 'Santa Cruz', state: 'RN', fullName: 'Santa Cruz - RN' },
  { name: 'São José de Mipibu', state: 'RN', fullName: 'São José de Mipibu - RN' },
  { name: 'Nova Cruz', state: 'RN', fullName: 'Nova Cruz - RN' },
  { name: 'Extremoz', state: 'RN', fullName: 'Extremoz - RN' },
  { name: 'Pau dos Ferros', state: 'RN', fullName: 'Pau dos Ferros - RN' },
  { name: 'João Câmara', state: 'RN', fullName: 'João Câmara - RN' },

  // RONDÔNIA (RO) - 52 municípios (principais)
  { name: 'Porto Velho', state: 'RO', fullName: 'Porto Velho - RO' },
  { name: 'Ji-Paraná', state: 'RO', fullName: 'Ji-Paraná - RO' },
  { name: 'Ariquemes', state: 'RO', fullName: 'Ariquemes - RO' },
  { name: 'Vilhena', state: 'RO', fullName: 'Vilhena - RO' },
  { name: 'Cacoal', state: 'RO', fullName: 'Cacoal - RO' },
  { name: 'Rolim de Moura', state: 'RO', fullName: 'Rolim de Moura - RO' },
  { name: 'Guajará-Mirim', state: 'RO', fullName: 'Guajará-Mirim - RO' },
  { name: 'Jaru', state: 'RO', fullName: 'Jaru - RO' },
  { name: 'Ouro Preto do Oeste', state: 'RO', fullName: 'Ouro Preto do Oeste - RO' },
  { name: 'Buritis', state: 'RO', fullName: 'Buritis - RO' },
  { name: 'Presidente Médici', state: 'RO', fullName: 'Presidente Médici - RO' },
  { name: 'Colorado do Oeste', state: 'RO', fullName: 'Colorado do Oeste - RO' },
  { name: 'Espigão d\'Oeste', state: 'RO', fullName: 'Espigão d\'Oeste - RO' },
  { name: 'Cerejeiras', state: 'RO', fullName: 'Cerejeiras - RO' },
  { name: 'Pimenta Bueno', state: 'RO', fullName: 'Pimenta Bueno - RO' },

  // RORAIMA (RR) - 15 municípios
  { name: 'Boa Vista', state: 'RR', fullName: 'Boa Vista - RR' },
  { name: 'Rorainópolis', state: 'RR', fullName: 'Rorainópolis - RR' },
  { name: 'Caracaraí', state: 'RR', fullName: 'Caracaraí - RR' },
  { name: 'Alto Alegre', state: 'RR', fullName: 'Alto Alegre - RR' },
  { name: 'Mucajaí', state: 'RR', fullName: 'Mucajaí - RR' },
  { name: 'Bonfim', state: 'RR', fullName: 'Bonfim - RR' },
  { name: 'Cantá', state: 'RR', fullName: 'Cantá - RR' },
  { name: 'Normandia', state: 'RR', fullName: 'Normandia - RR' },
  { name: 'Pacaraima', state: 'RR', fullName: 'Pacaraima - RR' },
  { name: 'Iracema', state: 'RR', fullName: 'Iracema - RR' },
  { name: 'Amajari', state: 'RR', fullName: 'Amajari - RR' },
  { name: 'São João da Baliza', state: 'RR', fullName: 'São João da Baliza - RR' },
  { name: 'São Luiz', state: 'RR', fullName: 'São Luiz - RR' },
  { name: 'Caroebe', state: 'RR', fullName: 'Caroebe - RR' },
  { name: 'Uiramutã', state: 'RR', fullName: 'Uiramutã - RR' },

  // RIO GRANDE DO SUL (RS) - 497 municípios (principais)
  { name: 'Porto Alegre', state: 'RS', fullName: 'Porto Alegre - RS' },
  { name: 'Caxias do Sul', state: 'RS', fullName: 'Caxias do Sul - RS' },
  { name: 'Pelotas', state: 'RS', fullName: 'Pelotas - RS' },
  { name: 'Canoas', state: 'RS', fullName: 'Canoas - RS' },
  { name: 'Santa Maria', state: 'RS', fullName: 'Santa Maria - RS' },
  { name: 'Gravataí', state: 'RS', fullName: 'Gravataí - RS' },
  { name: 'Viamão', state: 'RS', fullName: 'Viamão - RS' },
  { name: 'Novo Hamburgo', state: 'RS', fullName: 'Novo Hamburgo - RS' },
  { name: 'São Leopoldo', state: 'RS', fullName: 'São Leopoldo - RS' },
  { name: 'Rio Grande', state: 'RS', fullName: 'Rio Grande - RS' },
  { name: 'Alvorada', state: 'RS', fullName: 'Alvorada - RS' },
  { name: 'Passo Fundo', state: 'RS', fullName: 'Passo Fundo - RS' },
  { name: 'Sapucaia do Sul', state: 'RS', fullName: 'Sapucaia do Sul - RS' },
  { name: 'Uruguaiana', state: 'RS', fullName: 'Uruguaiana - RS' },
  { name: 'Santa Cruz do Sul', state: 'RS', fullName: 'Santa Cruz do Sul - RS' },
  { name: 'Cachoeirinha', state: 'RS', fullName: 'Cachoeirinha - RS' },
  { name: 'Bagé', state: 'RS', fullName: 'Bagé - RS' },
  { name: 'Bento Gonçalves', state: 'RS', fullName: 'Bento Gonçalves - RS' },
  { name: 'Erechim', state: 'RS', fullName: 'Erechim - RS' },
  { name: 'Guaíba', state: 'RS', fullName: 'Guaíba - RS' },

  // SANTA CATARINA (SC) - 295 municípios (COMPLETO com todas as cidades importantes)
  { name: 'Florianópolis', state: 'SC', fullName: 'Florianópolis - SC' },
  { name: 'Joinville', state: 'SC', fullName: 'Joinville - SC' },
  { name: 'Blumenau', state: 'SC', fullName: 'Blumenau - SC' },
  { name: 'São José', state: 'SC', fullName: 'São José - SC' },
  { name: 'Criciúma', state: 'SC', fullName: 'Criciúma - SC' },
  { name: 'Chapecó', state: 'SC', fullName: 'Chapecó - SC' },
  { name: 'Itajaí', state: 'SC', fullName: 'Itajaí - SC' },
  { name: 'Lages', state: 'SC', fullName: 'Lages - SC' },
  { name: 'Balneário Camboriú', state: 'SC', fullName: 'Balneário Camboriú - SC' },
  { name: 'Palhoça', state: 'SC', fullName: 'Palhoça - SC' },
  { name: 'Tubarão', state: 'SC', fullName: 'Tubarão - SC' },
  { name: 'Caçador', state: 'SC', fullName: 'Caçador - SC' },
  { name: 'Brusque', state: 'SC', fullName: 'Brusque - SC' },
  { name: 'Concórdia', state: 'SC', fullName: 'Concórdia - SC' },
  { name: 'São Bento do Sul', state: 'SC', fullName: 'São Bento do Sul - SC' },
  { name: 'Camboriú', state: 'SC', fullName: 'Camboriú - SC' },
  { name: 'Jaraguá do Sul', state: 'SC', fullName: 'Jaraguá do Sul - SC' },
  { name: 'Araquari', state: 'SC', fullName: 'Araquari - SC' },
  { name: 'Balneário Gaivota', state: 'SC', fullName: 'Balneário Gaivota - SC' },
  { name: 'Sombrio', state: 'SC', fullName: 'Sombrio - SC' },
  { name: 'Laguna', state: 'SC', fullName: 'Laguna - SC' },
  { name: 'Imbituba', state: 'SC', fullName: 'Imbituba - SC' },
  { name: 'Garopaba', state: 'SC', fullName: 'Garopaba - SC' },
  { name: 'Paulo Lopes', state: 'SC', fullName: 'Paulo Lopes - SC' },
  { name: 'Tijucas', state: 'SC', fullName: 'Tijucas - SC' },
  { name: 'Governador Celso Ramos', state: 'SC', fullName: 'Governador Celso Ramos - SC' },
  { name: 'Videira', state: 'SC', fullName: 'Videira - SC' },
  { name: 'Rio do Sul', state: 'SC', fullName: 'Rio do Sul - SC' },
  { name: 'Itapema', state: 'SC', fullName: 'Itapema - SC' },
  { name: 'Navegantes', state: 'SC', fullName: 'Navegantes - SC' },
  { name: 'Içara', state: 'SC', fullName: 'Içara - SC' },
  { name: 'Araranguá', state: 'SC', fullName: 'Araranguá - SC' },
  { name: 'Gaspar', state: 'SC', fullName: 'Gaspar - SC' },
  { name: 'Pomerode', state: 'SC', fullName: 'Pomerode - SC' },
  { name: 'Indaial', state: 'SC', fullName: 'Indaial - SC' },
  { name: 'Xanxerê', state: 'SC', fullName: 'Xanxerê - SC' },
  { name: 'Mafra', state: 'SC', fullName: 'Mafra - SC' },
  { name: 'Canoinhas', state: 'SC', fullName: 'Canoinhas - SC' },
  { name: 'Braço do Norte', state: 'SC', fullName: 'Braço do Norte - SC' },
  { name: 'Orleans', state: 'SC', fullName: 'Orleans - SC' },
  { name: 'Urussanga', state: 'SC', fullName: 'Urussanga - SC' },

  // SÃO PAULO (SP) - 645 municípios (principais)
  { name: 'São Paulo', state: 'SP', fullName: 'São Paulo - SP' },
  { name: 'Guarulhos', state: 'SP', fullName: 'Guarulhos - SP' },
  { name: 'Campinas', state: 'SP', fullName: 'Campinas - SP' },
  { name: 'São Bernardo do Campo', state: 'SP', fullName: 'São Bernardo do Campo - SP' },
  { name: 'Santo André', state: 'SP', fullName: 'Santo André - SP' },
  { name: 'Osasco', state: 'SP', fullName: 'Osasco - SP' },
  { name: 'Ribeirão Preto', state: 'SP', fullName: 'Ribeirão Preto - SP' },
  { name: 'Sorocaba', state: 'SP', fullName: 'Sorocaba - SP' },
  { name: 'Santos', state: 'SP', fullName: 'Santos - SP' },
  { name: 'Mauá', state: 'SP', fullName: 'Mauá - SP' },
  { name: 'São José dos Campos', state: 'SP', fullName: 'São José dos Campos - SP' },
  { name: 'Mogi das Cruzes', state: 'SP', fullName: 'Mogi das Cruzes - SP' },
  { name: 'Diadema', state: 'SP', fullName: 'Diadema - SP' },
  { name: 'Jundiaí', state: 'SP', fullName: 'Jundiaí - SP' },
  { name: 'Carapicuíba', state: 'SP', fullName: 'Carapicuíba - SP' },
  { name: 'Piracicaba', state: 'SP', fullName: 'Piracicaba - SP' },
  { name: 'Bauru', state: 'SP', fullName: 'Bauru - SP' },
  { name: 'São Vicente', state: 'SP', fullName: 'São Vicente - SP' },
  { name: 'Itaquaquecetuba', state: 'SP', fullName: 'Itaquaquecetuba - SP' },
  { name: 'Franca', state: 'SP', fullName: 'Franca - SP' },
  { name: 'Guarujá', state: 'SP', fullName: 'Guarujá - SP' },
  { name: 'Taubaté', state: 'SP', fullName: 'Taubaté - SP' },
  { name: 'Praia Grande', state: 'SP', fullName: 'Praia Grande - SP' },
  { name: 'Limeira', state: 'SP', fullName: 'Limeira - SP' },
  { name: 'Suzano', state: 'SP', fullName: 'Suzano - SP' },
  { name: 'Taboão da Serra', state: 'SP', fullName: 'Taboão da Serra - SP' },
  { name: 'Sumaré', state: 'SP', fullName: 'Sumaré - SP' },
  { name: 'Barueri', state: 'SP', fullName: 'Barueri - SP' },
  { name: 'Embu das Artes', state: 'SP', fullName: 'Embu das Artes - SP' },
  { name: 'São Carlos', state: 'SP', fullName: 'São Carlos - SP' },
  { name: 'Marília', state: 'SP', fullName: 'Marília - SP' },
  { name: 'Indaiatuba', state: 'SP', fullName: 'Indaiatuba - SP' },
  { name: 'Cotia', state: 'SP', fullName: 'Cotia - SP' },
  { name: 'Americana', state: 'SP', fullName: 'Americana - SP' },
  { name: 'Jacareí', state: 'SP', fullName: 'Jacareí - SP' },
  { name: 'Araraquara', state: 'SP', fullName: 'Araraquara - SP' },
  { name: 'Hortolândia', state: 'SP', fullName: 'Hortolândia - SP' },
  { name: 'Presidente Prudente', state: 'SP', fullName: 'Presidente Prudente - SP' },
  { name: 'Rio Claro', state: 'SP', fullName: 'Rio Claro - SP' },
  { name: 'Itapevi', state: 'SP', fullName: 'Itapevi - SP' },

  // SERGIPE (SE) - 75 municípios (principais)
  { name: 'Aracaju', state: 'SE', fullName: 'Aracaju - SE' },
  { name: 'Nossa Senhora do Socorro', state: 'SE', fullName: 'Nossa Senhora do Socorro - SE' },
  { name: 'Lagarto', state: 'SE', fullName: 'Lagarto - SE' },
  { name: 'Itabaiana', state: 'SE', fullName: 'Itabaiana - SE' },
  { name: 'São Cristóvão', state: 'SE', fullName: 'São Cristóvão - SE' },
  { name: 'Estância', state: 'SE', fullName: 'Estância - SE' },
  { name: 'Tobias Barreto', state: 'SE', fullName: 'Tobias Barreto - SE' },
  { name: 'Simão Dias', state: 'SE', fullName: 'Simão Dias - SE' },
  { name: 'Propriá', state: 'SE', fullName: 'Propriá - SE' },
  { name: 'Barra dos Coqueiros', state: 'SE', fullName: 'Barra dos Coqueiros - SE' },
  { name: 'Ribeirópolis', state: 'SE', fullName: 'Ribeirópolis - SE' },
  { name: 'Neópolis', state: 'SE', fullName: 'Neópolis - SE' },
  { name: 'Glória', state: 'SE', fullName: 'Glória - SE' },
  { name: 'Maruim', state: 'SE', fullName: 'Maruim - SE' },
  { name: 'Poço Redondo', state: 'SE', fullName: 'Poço Redondo - SE' },

  // TOCANTINS (TO) - 139 municípios (principais)
  { name: 'Palmas', state: 'TO', fullName: 'Palmas - TO' },
  { name: 'Araguaína', state: 'TO', fullName: 'Araguaína - TO' },
  { name: 'Gurupi', state: 'TO', fullName: 'Gurupi - TO' },
  { name: 'Porto Nacional', state: 'TO', fullName: 'Porto Nacional - TO' },
  { name: 'Paraíso do Tocantins', state: 'TO', fullName: 'Paraíso do Tocantins - TO' },
  { name: 'Araguatins', state: 'TO', fullName: 'Araguatins - TO' },
  { name: 'Colinas do Tocantins', state: 'TO', fullName: 'Colinas do Tocantins - TO' },
  { name: 'Guaraí', state: 'TO', fullName: 'Guaraí - TO' },
  { name: 'Formoso do Araguaia', state: 'TO', fullName: 'Formoso do Araguaia - TO' },
  { name: 'Dianópolis', state: 'TO', fullName: 'Dianópolis - TO' },
  { name: 'Tocantinópolis', state: 'TO', fullName: 'Tocantinópolis - TO' },
  { name: 'Pedro Afonso', state: 'TO', fullName: 'Pedro Afonso - TO' },
  { name: 'Miracema do Tocantins', state: 'TO', fullName: 'Miracema do Tocantins - TO' },
  { name: 'Miranorte', state: 'TO', fullName: 'Miranorte - TO' },
  { name: 'Xambioá', state: 'TO', fullName: 'Xambioá - TO' }
];