// Lista de bairros de Recife e RMR organizados por região

export interface NeighborhoodRegion {
  region: string;
  neighborhoods: string[];
}

export const recifeNeighborhoodsByRegion: NeighborhoodRegion[] = [
  {
    region: "RPA 1 - Centro",
    neighborhoods: [
      "Recife",
      "Santo Amaro",
      "Boa Vista",
      "Cabanga",
      "Ilha do Leite",
      "Paissandu",
      "Santo Antonio",
      "São José",
      "Soledade",
      "Coelhos",
    ],
  },
  {
    region: "RPA 2 - Norte",
    neighborhoods: [
      "Alto Santa Terezinha",
      "Água Fria",
      "Arruda",
      "Bomba do Hemetério",
      "Cajueiro",
      "Campina do Barreto",
      "Campo Grande",
      "Dois Unidos",
      "Encruzilhada",
      "Fundão",
      "Hipódromo",
      "Linha do Tiro",
      "Peixinhos",
      "Ponto de Parada",
      "Porto da Madeira",
      "Rosarinho",
      "Torreão",
    ],
  },
  {
    region: "RPA 3 - Noroeste",
    neighborhoods: [
      "Aflitos",
      "Alto do Mandú",
      "Apipucos",
      "Casa Amarela",
      "Casa Forte",
      "Cidade Universitária",
      "Derby",
      "Dois Irmãos",
      "Espinheiro",
      "Graças",
      "Jaqueira",
      "Monteiro",
      "Parnamirim",
      "Poço da Panela",
      "Santana",
      "Sítio dos Pintos",
      "Tamarineira",
      "Vasco da Gama",
    ],
  },
  {
    region: "RPA 4 - Sudeste",
    neighborhoods: [
      "Boa Viagem",
      "Brasília Teimosa",
      "Cordeiro",
      "Ilha do Retiro",
      "Imbiribeira",
      "Ipsep",
      "Madalena",
      "Prado",
      "Torre",
      "Torrões",
      "Zumbi",
    ],
  },
  {
    region: "RPA 5 - Sudoeste",
    neighborhoods: [
      "Afogados",
      "Bongi",
      "Caçote",
      "Curado",
      "Estância",
      "Jardim São Paulo",
      "Jiquiá",
      "Mangueira",
      "Mustardinha",
      "San Martin",
      "Sancho",
      "Tejipió",
      "Totó",
    ],
  },
  {
    region: "RPA 6 - Oeste",
    neighborhoods: [
      "Alto do Céu",
      "Alto José Bonifácio",
      "Alto José do Pinho",
      "Beberibe",
      "Brejo da Guabiraba",
      "Brejo de Beberibe",
      "Córrego do Jenipapo",
      "Dois Carneiros",
      "Guabiraba",
      "Ilha de Joana Bezerra",
      "Macaxeira",
      "Mangabeira",
      "Nova Descoberta",
      "Passarinho",
      "Porto",
      "Sucupira",
      "Vila da Paz",
    ],
  },
  {
    region: "Olinda",
    neighborhoods: [
      "Olinda - Bairro Novo",
      "Olinda - Casa Caiada",
      "Olinda - Rio Doce",
      "Olinda - Jardim Atlântico",
      "Olinda - Peixinhos (Olinda)",
      "Olinda - Salgadinho",
      "Olinda - Varadouro",
      "Olinda - Carmo",
      "Olinda - Amaro Branco",
      "Olinda - Bultrins",
      "Olinda - Ouro Preto",
      "Olinda - Jardim Fragoso",
      "Olinda - Águas Compridas",
      "Olinda - Sapucaia",
      "Olinda - Centro",
    ],
  },
  {
    region: "Jaboatão dos Guararapes",
    neighborhoods: [
      "Jaboatão - Piedade",
      "Jaboatão - Candeias",
      "Jaboatão - Barra de Jangada",
      "Jaboatão - Prazeres",
      "Jaboatão - Cavaleiro",
      "Jaboatão - Centro",
      "Jaboatão - Curado (Jaboatão)",
      "Jaboatão - Jardim Jordão",
      "Jaboatão - Marcos Freire",
      "Jaboatão - Muribeca",
      "Jaboatão - Socorro",
      "Jaboatão - Guararapes",
    ],
  },
  {
    region: "Paulista",
    neighborhoods: [
      "Paulista - Janga",
      "Paulista - Pau Amarelo",
      "Paulista - Maria Farinha",
      "Paulista - Arthur Lundgren",
      "Paulista - Centro (Paulista)",
      "Paulista - Maranguape",
      "Paulista - Nobre",
      "Paulista - Jardim Paulista",
    ],
  },
  {
    region: "Cabo de Santo Agostinho",
    neighborhoods: [
      "Cabo - Centro",
      "Cabo - Ponte dos Carvalhos",
      "Cabo - Garapu",
      "Cabo - Suape",
      "Cabo - Paiva",
      "Cabo - Charneca",
    ],
  },
  {
    region: "Camaragibe",
    neighborhoods: [
      "Camaragibe - Centro",
      "Camaragibe - Aldeia",
      "Camaragibe - Tabatinga",
      "Camaragibe - Timbi",
      "Camaragibe - Vale das Pedreiras",
    ],
  },
  {
    region: "Outras Cidades RMR",
    neighborhoods: [
      "Igarassu - Centro",
      "Igarassu - Cruz de Rebouças",
      "Abreu e Lima - Centro",
      "Abreu e Lima - Caetés",
      "São Lourenço da Mata - Centro",
      "São Lourenço da Mata - Camela",
      "Ipojuca - Centro",
      "Ipojuca - Porto de Galinhas",
      "Moreno - Centro",
      "Itamaracá - Centro",
      "Itapissuma - Centro",
      "Araçoiaba - Centro",
    ],
  },
];

// Lista flat para compatibilidade (busca, validação, etc.)
export const recifeNeighborhoods: string[] = recifeNeighborhoodsByRegion.flatMap(
  (r) => r.neighborhoods
);

// Bairros mais populares/centrais para destaque
export const popularNeighborhoods = [
  "Boa Viagem",
  "Pina",
  "Recife",
  "Santo Amaro",
  "Boa Vista",
  "Graças",
  "Espinheiro",
  "Aflitos",
  "Derby",
  "Casa Forte",
  "Tamarineira",
  "Madalena",
  "Torre",
  "Cordeiro",
  "Imbiribeira",
];

// Exportar objeto com nome e bairros
export const recifeData = {
  city: "Recife",
  state: "PE",
  fullName: "Recife - PE",
  neighborhoods: recifeNeighborhoods,
  popularNeighborhoods: popularNeighborhoods,
};
