-- Inserir cadastro pendente de teste para Gabriela de Recife
INSERT INTO cadastros_pendentes (
  name,
  real_name,
  display_name,
  email,
  phone,
  age,
  location,
  height,
  image,
  gallery,
  services,
  cities_served,
  description,
  price_per_hour,
  has_own_location,
  accepts_travel,
  professional_name,
  status,
  submitted_at
) VALUES (
  'Gabriela',
  'Gabriela Silva',
  'Gabriela',
  'gabriela.recife@exemplo.com',
  '(81) 99999-8888',
  23,
  'Boa Viagem, Recife',
  '1,65m',
  'https://images.unsplash.com/photo-1494790108755-2616b332c74c?w=400&h=500&fit=crop&crop=face',
  ARRAY['https://images.unsplash.com/photo-1494790108755-2616b332c74c?w=400&h=500&fit=crop&crop=face', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop&crop=face'],
  ARRAY['Acompanhante de luxo', 'Jantar romântico', 'Eventos sociais'],
  ARRAY['Recife', 'Boa Viagem', 'Olinda'],
  'Acompanhante carinhosa e educada, ideal para eventos sociais e jantares românticos.',
  '200',
  true,
  true,
  'Gabriela',
  'pending',
  NOW()
);